### ISSUE TITLE
Padding Strategy for RSA encrypt/decrypt

### ISSUE THREAD

**Issue by rozumem** [rubo/flame#2]
Main question: 

What padding strategy do the RSA encrpyt/decrypt methods use in flame? Is it PKCS1_PADDING by default? Something else?

--- Context ---

I have successfully generated RSA key pair using your library and have tested it successfully in flash by encrypting/decrypting various strings. I am now try to encrypt a string using the flame library and decrypt the result using Ruby's OpenSSL::RSA library.

Flash:
sample string = "testfootest"
Base64 urlsafe encoded result:

"Zi1e8kz9TVb99EU0aZQ7heY4ecN7v6WFeR8Il6tKYnsuSF9MUZq8ReY2a9lslMNALBggi7Wzneq2LDTdeNPllA=="

Ruby:
I create the RSA key pair using the private key generated by flame.
When I try to decrypt the encrypted result, I get the following error:

OpenSSL::PKey::RSAError: padding check failed
    from (irb):12:in `public_decrypt'
    from (irb):12
    from /Users/dhracker/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:47:in`start'
    from /Users/dhracker/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands/console.rb:8:in `start'
    from /Users/dhracker/.rvm/gems/ruby-1.9.3-p194/gems/railties-3.2.8/lib/rails/commands.rb:41:in`<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in`<main>'

**Comment by rubo** [comment]
For key exchange, there are two padding options currently provided by the library -- OAEP and PKCS 1; and for signatures -- PSS and PKCS 1. However, you may implement any other padding algorithms by inheriting from AsymmetricKeyExchangeFormatter/AsymmetricKeyExchangeDeformatter or AsymmetricSignatureFormatter/AsymmetricSignatureDeformatter for key exchange or signatures correspondingly.
And note that you should never ever use RSA class directly. Only by using any derivations of abovementioned classes.
