### ISSUE TITLE
RSA 512 public key length is too short

### ISSUE THREAD

**Issue by rozumem** [rubo/flame#3]
Using Flame, here is a sample public key generated:

-----BEGIN PUBLIC KEY-----
MEoCAQACQLbkpbDFbZ54bM5ybwwdCqsUHjxWQF4B0Q1sAOBFEYdpxZJZ8dAzycPz
IgSlPc8yqjeqwJQtvCpktrntALpX1ksCAwEAAQ==
-----END PUBLIC KEY-----

Using Ruby OpenSSL, here is a sample public key generated:

-----BEGIN PUBLIC KEY-----
MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMiZRXRL+l/m+HSu+QIikirFDTyTtXo4
PJZ2WU3nXYOFHsLrdwrBTR7KDYs+/w64TI7PuiuKXyKDqtRjf0UxHvUCAwEAAQ==
-----END PUBLIC KEY-----

> OpenSSL::PKey::RSA.new(512).public_key

Why is there a difference in the length?

**Comment by rubo** [comment]
How did you generate it with Flame? Please provide the code.

**Comment by rozumem** [comment]
Note: Private key lengths match for 512.

**Comment by rozumem** [comment]
Will provide code shortly. Meanwhile, I have opened another issue - https://github.com/rubo/flame/issues/4 - appreciate your quick response! Thanks for the help.
