### ISSUE TITLE
Encrypt using RSA private key instead of public key

### ISSUE THREAD

**Issue by rozumem** [rubo/flame#4]
It seems that RSAPKCS1KeyExchangeFormatter encrypts data using the public key. 

In my use case, I only want one "provider" to be able to send several "consumers" encrypted messages. Thus, I want the "provider" (i.e. my flash app) to encrypt data using the private key and my "consumers" to decrypt data using the public key. 

Is there a straightforward way I can create a cipher using the private RSA key instead of the public key?

Thanks!

**Comment by rubo** [comment]
Although that's not what RSA is designed for, you can do that. Mathematically it will work just fine. However, I'd not recommend that. And yes, RSAPKCS1KeyExchangeFormatter uses the public key to encrypt the data. What you want to do is similar to signing operation but it's not signing. You can use the decrypt() method of RSA for encryption and the encrypt() method for decryption. Thus, it will use the private key to encrypt and the public key to decrypt. That is the easiest way to go but the most insecure, indeed. It's always better to have some padding as I recommended you when answered to one of your previous questions.
