### ISSUE TITLE
Bug when importing from XML data only has modulus and exponent (public key only)

### ISSUE THREAD

**Issue by hoangbinh** [rubo/flame#5]
Issue in line 277, class RSA. I replaced:
_isKeyParametersGenerated = _d != null || _useCRT;
by:
_isKeyParametersGenerated = true;

**Comment by rubo** [comment]
Seems you're right, that's a bug. What exactly was your issue?

**Comment by hoangbinh** [comment]
I use your lib for verifying signatures in my flash app. Because it is a client app, it only has my publickey that is imported by the function RSA.fromXMLString. Your code in this function set _isKeyParametersGenerated = false. When I call RSAPKCS1SignatureDeformatter.verifySignature, this func call RSA.encrypt. In encrypt, because _isKeyParametersGenerated == false, a new key is generated. So verifySignature always return false.
It took me a day to find this issue. :-(

**Comment by rubo** [comment]
Nice catch. Thank you.
